<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
        <ItemGroup>
          <ProjectReference Include="..\Fc25Draft.Core\Fc25Draft.Core.csproj" />
          <ProjectReference Include="..\Fc25Draft.Infra\Fc25Draft.Infra.csproj" />
        </ItemGroup>
</Project>
