create table "AdminActionsLog"
(
    "ActionId" uuid not null primary key,
    "ActionType" integer not null,
    "PerformedBy" varchar(120) not null,
    "PayloadJson" text not null,
    "CreatedAtUtc" timestamptz not null
);

create table "Drafts"
(
    "DraftId" uuid not null primary key,
    "Name" text not null,
    "TotalTeams" integer not null,
    "TotalRounds" integer not null,
    "CreatedAtUtc" timestamptz not null
);

create table "MarketCycles"
(
    "CycleId" uuid not null primary key,
    "Name" varchar(120) not null,
    "Status" integer not null,
    "StartsAtUtc" timestamptz not null,
    "EndsAtUtc" timestamptz not null,
    "Notes" varchar(500),
    "CreatedAtUtc" timestamptz not null,
    "UpdatedAtUtc" timestamptz not null
);

create table "Positions"
(
    "PositionId" smallint not null primary key,
    "Name" varchar(40) not null
);

create table "Teams"
(
    "TeamId" uuid not null primary key,
    "TeamName" varchar(80) not null,
    "OwnerName" varchar(80),
    "Token" varchar(80) not null,
    "Budget" numeric(18,2) not null default 0,
    "BudgetBlocked" numeric(18,2) not null default 0
);

create table "Token_Administrador"
(
    "AdminTokenId" integer generated by default as identity primary key,
    "Token" uuid not null
);

create table "DraftRounds"
(
    "DraftId" uuid not null,
    "RoundNumber" integer not null,
    "OverallMin" integer,
    "OverallMax" integer,
    primary key ("DraftId", "RoundNumber")
);

create table "Players"
(
    "PlayerId" integer generated by default as identity primary key,
    "Name" varchar(80) not null,
    "Age" integer,
    "Overall" integer not null,
    "PreviousOverall" integer,
    "Status" integer not null default 1,
    "PositionId" smallint not null,
    "PlayerGuid" uuid not null,
    "CurrentTeamId" uuid
);

create table "BudgetLedgers"
(
    "BudgetLedgerId" uuid not null primary key,
    "TeamId" uuid not null,
    "DataUtc" timestamptz not null,
    "Tipo" varchar(10) not null,
    "Origem" varchar(50) not null,
    "Valor" numeric(18,2) not null,
    "Descricao" varchar(256),
    constraint "CK_BudgetLedger_Tipo" check ("Tipo" in ('CREDIT','DEBIT')),
    constraint "CK_BudgetLedger_Valor" check ("Valor" > 0)
);

create table "DraftPicks"
(
    "DraftId" uuid not null,
    "OverallPick" integer not null,
    "RoundNumber" integer not null,
    "PickInRound" integer not null,
    "TeamId" uuid not null,
    "PlayerId" integer,
    "PickedAtUtc" timestamptz,
    primary key ("DraftId", "OverallPick")
);

create table "MarketItems"
(
    "ItemId" uuid not null primary key,
    "CycleId" uuid not null,
    "PlayerId" integer not null,
    "Status" integer not null,
    "BasePrice" numeric(18,2) not null,
    "BuyNowPrice" numeric(18,2),
    "MinIncrement" numeric(18,2) not null,
    "CurrentLeaderAmount" numeric(18,2),
    "CurrentLeaderTeamId" uuid,
    "WinnerTeamId" uuid,
    "CreatedAtUtc" timestamptz not null,
    "LastUpdateUtc" timestamptz not null,
    "ExpiresAtUtc" timestamptz not null,
    "PublishedAtUtc" timestamptz
);

create table "TeamRosters"
(
    "TeamId" uuid not null,
    "PlayerId" integer not null,
    primary key ("TeamId", "PlayerId")
);

create table "TransferHistories"
(
    "TransferId" uuid not null primary key,
    "PlayerId" integer not null,
    "FromTeamId" uuid,
    "ToTeamId" uuid,
    "Type" integer not null,
    "Amount" numeric(18,2),
    "Payout" numeric(18,2),
    "OldOverall" integer,
    "NewOverall" integer,
    "Notes" varchar(400),
    "PerformedBy" varchar(120),
    "OccurredAtUtc" timestamptz not null
);

create table "MarketBids"
(
    "BidId" uuid not null primary key,
    "ItemId" uuid not null,
    "TeamId" uuid not null,
    "Amount" numeric(18,2) not null,
    "CreatedAtUtc" timestamptz not null
);

insert into "Positions" ("PositionId", "Name") values
    (1, 'Goleiro'),
    (2, 'Zagueiro'),
    (3, 'Lateral/Ala Esquerdo'),
    (4, 'Lateral/Ala Direito'),
    (5, 'Volante'),
    (6, 'Meia Central'),
    (7, 'Meia Atacante'),
    (8, 'Meia/Ponta Esquerda'),
    (9, 'Meia/Ponta Direita'),
    (10, 'Atacante')
on conflict do nothing;
