// <auto-generated />
using System;
using Fc25Draft.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fc25Draft.Infra.Migrations
{
    [DbContext(typeof(DraftDbContext))]
    [Migration("20251125093000_AddSeasonCalendar")]
    partial class AddSeasonCalendar
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminActionsLog", b =>
                {
                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("ActionId");

                    b.HasIndex("ActionType", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AdminActionsLog_ActionType_CreatedAtUtc");

                    b.ToTable("AdminActionsLog", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminToken", b =>
                {
                    b.Property<int>("AdminTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminTokenId"));

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.HasKey("AdminTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Token_Administrador", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.Property<Guid>("BudgetLedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("BudgetLedgerId");

                    b.HasIndex("TeamId");

                    b.ToTable("BudgetLedgers");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Competition", b =>
                {
                    b.Property<Guid>("CompetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("CompetitionId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeasonId", "Name")
                        .IsUnique();

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Round", b =>
                {
                    b.Property<Guid>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoundId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CompetitionId", "Name")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Season", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.SeasonScheduleItem", b =>
                {
                    b.Property<Guid>("SeasonScheduleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("SeasonScheduleItemId");

                    b.HasIndex("RoundId");

                    b.HasIndex("SeasonId", "Order")
                        .IsUnique();

                    b.ToTable("SeasonSchedule");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTeams")
                        .HasColumnType("integer");

                    b.HasKey("DraftId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallPick")
                        .HasColumnType("integer");

                    b.Property<int>("PickInRound")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PickedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("DraftId", "OverallPick");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("\"PlayerId\" IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "RoundNumber", "PickInRound")
                        .IsUnique();

                    b.HasIndex("DraftId", "TeamId", "RoundNumber");

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("OverallMax")
                        .HasColumnType("integer");

                    b.Property<int?>("OverallMin")
                        .HasColumnType("integer");

                    b.HasKey("DraftId", "RoundNumber");

                    b.ToTable("DraftRounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketBid", b =>
                {
                    b.Property<Guid>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("BidId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ItemId", "CreatedAtUtc");

                    b.ToTable("MarketBids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketCycle", b =>
                {
                    b.Property<Guid>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CycleId");

                    b.ToTable("MarketCycles");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("BuyNowPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentLeaderAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CurrentLeaderTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinIncrement")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId");

                    b.HasIndex("CurrentLeaderTeamId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MarketItems_Player");

                    b.HasIndex("WinnerTeamId");

                    b.HasIndex("CycleId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("CycleId", "Status", "ExpiresAtUtc");

                    b.ToTable("MarketItems");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TargetTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("IX_MarketTransactions_Cycle");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_MarketTransactions_Item");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MarketTransactions_Player");

                    b.HasIndex("PlayerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Player_CreatedAt");

                    b.HasIndex("CycleId", "Type", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Cycle_Type_CreatedAt");

                    b.HasIndex("ItemId", "Type", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Item_Type_CreatedAt");

                    b.ToTable("MarketTransactions");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerGuid")
                        .HasColumnType("uuid");

                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.Property<int?>("QuickSellNewOverall")
                        .HasColumnType("integer");

                    b.Property<int?>("QuickSellOldOverall")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuickSellTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("PlayerId");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("PlayerGuid")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.HasIndex("Name", "PositionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("PositionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = (short)1,
                            Name = "Goleiro"
                        },
                        new
                        {
                            PositionId = (short)2,
                            Name = "Zagueiro"
                        },
                        new
                        {
                            PositionId = (short)3,
                            Name = "Lateral/Ala Esquerdo"
                        },
                        new
                        {
                            PositionId = (short)4,
                            Name = "Lateral/Ala Direito"
                        },
                        new
                        {
                            PositionId = (short)5,
                            Name = "Volante"
                        },
                        new
                        {
                            PositionId = (short)6,
                            Name = "Meia Central"
                        },
                        new
                        {
                            PositionId = (short)7,
                            Name = "Meia Atacante"
                        },
                        new
                        {
                            PositionId = (short)8,
                            Name = "Meia/Ponta Esquerda"
                        },
                        new
                        {
                            PositionId = (short)9,
                            Name = "Meia/Ponta Direita"
                        },
                        new
                        {
                            PositionId = (short)10,
                            Name = "Atacante"
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BudgetBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("OwnerName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("FromTeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NewOverall")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("OldOverall")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ToTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("TransferId");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("PerformedAtUtc");

                    b.HasIndex("ToTeamId");

                    b.HasIndex("PlayerId", "PerformedAtUtc");

                    b.ToTable("TransferHistories");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("DraftPicks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("DraftPicks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.DraftRound", "Round")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId", "RoundNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Player");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Rounds")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketBid", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.MarketItem", "Item")
                        .WithMany("Bids")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("MarketBids")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Competition", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Season", "Season")
                        .WithMany("Competitions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "CurrentLeaderTeam")
                        .WithMany("LeadingMarketItems")
                        .HasForeignKey("CurrentLeaderTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.MarketCycle", "Cycle")
                        .WithMany("Items")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("MarketItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "WinnerTeam")
                        .WithMany("WonMarketItems")
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentLeaderTeam");

                    b.Navigation("Cycle");

                    b.Navigation("Player");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fc25Draft.Core.Entities.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTeam");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Round", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Competition", "Competition")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.SeasonScheduleItem", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Season", "Season")
                        .WithMany("Schedule")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("TeamRosters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Navigation("Picks");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketCycle", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("MarketItems");

                    b.Navigation("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("LeadingMarketItems");

                    b.Navigation("MarketBids");

                    b.Navigation("Roster");

                    b.Navigation("WonMarketItems");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Competition", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Season", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
