// <auto-generated />
using System;
using Fc25Draft.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fc25Draft.Infra.Migrations
{
    [DbContext(typeof(DraftDbContext))]
    [Migration("20251028015904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminToken", b =>
                {
                    b.Property<int>("AdminTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminTokenId"));

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdminTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Token_Administrador", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Bid", b =>
                {
                    b.Property<Guid>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MarketItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BidId");

                    b.HasIndex("TeamId");

                    b.HasIndex("MarketItemId", "DataUtc")
                        .HasDatabaseName("IX_Bid_MarketItemId_DataUtc");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.Property<Guid>("BudgetLedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BudgetLedgerId");

                    b.HasIndex("TeamId", "DataUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_BudgetLedger_TeamId_DataUtc");

                    b.ToTable("BudgetLedgers", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetLedger_Tipo", "[Tipo] IN ('CREDIT','DEBIT')");

                            t.HasCheckConstraint("CK_BudgetLedger_Valor", "[Valor] > 0");
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("int");

                    b.Property<int>("TotalTeams")
                        .HasColumnType("int");

                    b.HasKey("DraftId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OverallPick")
                        .HasColumnType("int");

                    b.Property<int>("PickInRound")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DraftId", "OverallPick");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "RoundNumber", "PickInRound")
                        .IsUnique();

                    b.HasIndex("DraftId", "TeamId", "RoundNumber");

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int?>("OverallMax")
                        .HasColumnType("int");

                    b.Property<int?>("OverallMin")
                        .HasColumnType("int");

                    b.HasKey("DraftId", "RoundNumber");

                    b.ToTable("DraftRounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Overall")
                        .HasColumnType("int");

                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.HasKey("PlayerId");

                    b.HasIndex("PositionId");

                    b.HasIndex("Name", "PositionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PositionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = (short)1,
                            Name = "Goleiro"
                        },
                        new
                        {
                            PositionId = (short)2,
                            Name = "Zagueiro"
                        },
                        new
                        {
                            PositionId = (short)3,
                            Name = "Lateral/Ala Esquerdo"
                        },
                        new
                        {
                            PositionId = (short)4,
                            Name = "Lateral/Ala Direito"
                        },
                        new
                        {
                            PositionId = (short)5,
                            Name = "Volante"
                        },
                        new
                        {
                            PositionId = (short)6,
                            Name = "Meia Central"
                        },
                        new
                        {
                            PositionId = (short)7,
                            Name = "Meia Atacante"
                        },
                        new
                        {
                            PositionId = (short)8,
                            Name = "Meia/Ponta Esquerda"
                        },
                        new
                        {
                            PositionId = (short)9,
                            Name = "Meia/Ponta Direita"
                        },
                        new
                        {
                            PositionId = (short)10,
                            Name = "Atacante"
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("TeamToken")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.HasIndex("TeamToken")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamBudget", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TeamId");

                    b.ToTable("TeamBudgets");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.Property<Guid>("TransferHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DestinoTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrigemTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransferHistoryId");

                    b.HasIndex("DataUtc")
                        .HasDatabaseName("IX_TransferHistory_DataUtc");

                    b.HasIndex("DestinoTeamId");

                    b.HasIndex("OrigemTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("TransferHistories", t =>
                        {
                            t.HasCheckConstraint("CK_TransferHistory_Tipo", "[Tipo] IN ('MARKET_AUCTION','TEAM_SALE','TEAM_TRADE')");
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferMarketItem", b =>
                {
                    b.Property<Guid>("MarketItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFimUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LanceAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("MaiorLanceTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoComprarAgora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("VencedorTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MarketItemId");

                    b.HasIndex("MaiorLanceTeamId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_TransferMarketItem_Player_Open")
                        .HasFilter("[Status] = 'OPEN'");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TransferMarketItem_Status");

                    b.HasIndex("VencedorTeamId");

                    b.HasIndex("PlayerId", "Status")
                        .HasDatabaseName("IX_TransferMarketItem_Player_Status");

                    b.ToTable("TransferMarketItems", t =>
                        {
                            t.HasCheckConstraint("CK_TransferMarketItem_Status", "[Status] IN ('OPEN','SOLD','EXPIRED')");
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Bid", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.TransferMarketItem", "MarketItem")
                        .WithMany("Bids")
                        .HasForeignKey("MarketItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MarketItem");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("DraftPicks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("DraftPicks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.DraftRound", "Round")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId", "RoundNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Player");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Rounds")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamBudget", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithOne()
                        .HasForeignKey("Fc25Draft.Core.Entities.TeamBudget", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("TeamRosters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "DestinoTeam")
                        .WithMany()
                        .HasForeignKey("DestinoTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "OrigemTeam")
                        .WithMany()
                        .HasForeignKey("OrigemTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinoTeam");

                    b.Navigation("OrigemTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferMarketItem", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "MaiorLanceTeam")
                        .WithMany()
                        .HasForeignKey("MaiorLanceTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "VencedorTeam")
                        .WithMany()
                        .HasForeignKey("VencedorTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaiorLanceTeam");

                    b.Navigation("Player");

                    b.Navigation("VencedorTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Navigation("Picks");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferMarketItem", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
