// <auto-generated />
using System;
using Fc25Draft.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fc25Draft.Infra.Migrations
{
    [DbContext(typeof(DraftDbContext))]
    [Migration("20251029014513_Mercado_Sync6")]
    partial class Mercado_Sync6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminActionsLog", b =>
                {
                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ActionId");

                    b.HasIndex("ActionType", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AdminActionsLog_ActionType_CreatedAtUtc");

                    b.ToTable("AdminActionsLog", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminToken", b =>
                {
                    b.Property<int>("AdminTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminTokenId"));

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdminTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Token_Administrador", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.Property<Guid>("BudgetLedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BudgetLedgerId");

                    b.HasIndex("TeamId", "DataUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_BudgetLedger_TeamId_DataUtc");

                    b.ToTable("BudgetLedgers", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetLedger_Tipo", "[Tipo] IN ('CREDIT','DEBIT')");

                            t.HasCheckConstraint("CK_BudgetLedger_Valor", "[Valor] > 0");
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("int");

                    b.Property<int>("TotalTeams")
                        .HasColumnType("int");

                    b.HasKey("DraftId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OverallPick")
                        .HasColumnType("int");

                    b.Property<int>("PickInRound")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DraftId", "OverallPick");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "RoundNumber", "PickInRound")
                        .IsUnique();

                    b.HasIndex("DraftId", "TeamId", "RoundNumber");

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int?>("OverallMax")
                        .HasColumnType("int");

                    b.Property<int?>("OverallMin")
                        .HasColumnType("int");

                    b.HasKey("DraftId", "RoundNumber");

                    b.ToTable("DraftRounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketBid", b =>
                {
                    b.Property<Guid>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BidId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ItemId", "CreatedAtUtc");

                    b.ToTable("MarketBids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketCycle", b =>
                {
                    b.Property<Guid>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextCycleAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CycleId");

                    b.ToTable("MarketCycles");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyNowPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentLeaderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CurrentLeaderTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MinIncrement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItemId");

                    b.HasIndex("CurrentLeaderTeamId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MarketItems_Player");

                    b.HasIndex("WinnerTeamId");

                    b.HasIndex("CycleId", "Status", "ExpiresAtUtc");

                    b.ToTable("MarketItems");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Overall")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.HasKey("PlayerId");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("PlayerGuid")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.HasIndex("Name", "PositionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("PositionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = (short)1,
                            Name = "Goleiro"
                        },
                        new
                        {
                            PositionId = (short)2,
                            Name = "Zagueiro"
                        },
                        new
                        {
                            PositionId = (short)3,
                            Name = "Lateral/Ala Esquerdo"
                        },
                        new
                        {
                            PositionId = (short)4,
                            Name = "Lateral/Ala Direito"
                        },
                        new
                        {
                            PositionId = (short)5,
                            Name = "Volante"
                        },
                        new
                        {
                            PositionId = (short)6,
                            Name = "Meia Central"
                        },
                        new
                        {
                            PositionId = (short)7,
                            Name = "Meia Atacante"
                        },
                        new
                        {
                            PositionId = (short)8,
                            Name = "Meia/Ponta Esquerda"
                        },
                        new
                        {
                            PositionId = (short)9,
                            Name = "Meia/Ponta Direita"
                        },
                        new
                        {
                            PositionId = (short)10,
                            Name = "Atacante"
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Budget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BudgetBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("OwnerName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("FromTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ToTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TransferId");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("ToTeamId");

                    b.HasIndex("PlayerId", "PerformedAtUtc");

                    b.ToTable("TransferHistories");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("DraftPicks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("DraftPicks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.DraftRound", "Round")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId", "RoundNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Player");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Rounds")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketBid", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.MarketItem", "Item")
                        .WithMany("Bids")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("MarketBids")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "CurrentLeaderTeam")
                        .WithMany("LeadingMarketItems")
                        .HasForeignKey("CurrentLeaderTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.MarketCycle", "Cycle")
                        .WithMany("Items")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("MarketItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "WinnerTeam")
                        .WithMany("WonMarketItems")
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentLeaderTeam");

                    b.Navigation("Cycle");

                    b.Navigation("Player");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fc25Draft.Core.Entities.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTeam");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("TeamRosters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Navigation("Picks");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketCycle", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("MarketItems");

                    b.Navigation("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("LeadingMarketItems");

                    b.Navigation("MarketBids");

                    b.Navigation("Roster");

                    b.Navigation("WonMarketItems");
                });
#pragma warning restore 612, 618
        }
    }
}
