// <auto-generated />
using System;
using Fc25Draft.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fc25Draft.Infra.Migrations
{
    [DbContext(typeof(DraftDbContext))]
    [Migration("20260827190851_AddTeamLineupChangeLog")]
    partial class AddTeamLineupChangeLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminActionsLog", b =>
                {
                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("ActionId");

                    b.HasIndex("ActionType", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AdminActionsLog_ActionType_CreatedAtUtc");

                    b.ToTable("AdminActionsLog", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminToken", b =>
                {
                    b.Property<Guid>("AdminTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("AdminTokenId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_AdminTokens_IsActive");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_AdminTokens_Token_Unique");

                    b.ToTable("AdminTokens");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.Property<Guid>("BudgetLedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BudgetLedgerId");

                    b.HasIndex("TeamId", "DataUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_BudgetLedger_TeamId_DataUtc");

                    b.ToTable("BudgetLedgers", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetLedger_Tipo", "\"Tipo\" IN ('CREDIT','DEBIT')");

                            t.HasCheckConstraint("CK_BudgetLedger_Valor", "\"Valor\" > 0");
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTeams")
                        .HasColumnType("integer");

                    b.HasKey("DraftId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallPick")
                        .HasColumnType("integer");

                    b.Property<int>("PickInRound")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PickedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("DraftId", "OverallPick");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "PlayerId")
                        .IsUnique()
                        .HasFilter("\"PlayerId\" IS NOT NULL");

                    b.HasIndex("DraftId", "RoundNumber", "PickInRound")
                        .IsUnique();

                    b.HasIndex("DraftId", "TeamId", "RoundNumber");

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("OverallMax")
                        .HasColumnType("integer");

                    b.Property<int?>("OverallMin")
                        .HasColumnType("integer");

                    b.HasKey("DraftId", "RoundNumber");

                    b.ToTable("DraftRounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.HallOfFameEntry", b =>
                {
                    b.Property<Guid>("HallOfFameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tecnico")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Temporada")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TimeCampeao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("HallOfFameId");

                    b.ToTable("HallOfFame");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAtUtc");

                    b.ToTable("IdempotencyKeys");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Liga", b =>
                {
                    b.Property<Guid>("LigaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CampeaoTimeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalRodadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8);

                    b.HasKey("LigaId");

                    b.HasIndex("CampeaoTimeId");

                    b.ToTable("Ligas");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaClassificacao", b =>
                {
                    b.Property<Guid>("ClassificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CartoesAmarelos")
                        .HasColumnType("integer");

                    b.Property<int>("CartoesVermelhos")
                        .HasColumnType("integer");

                    b.Property<int>("Derrotas")
                        .HasColumnType("integer");

                    b.Property<int>("Empates")
                        .HasColumnType("integer");

                    b.Property<int>("GolsContra")
                        .HasColumnType("integer");

                    b.Property<int>("GolsPro")
                        .HasColumnType("integer");

                    b.Property<int?>("Grupo")
                        .HasColumnType("integer");

                    b.Property<int>("Jogos")
                        .HasColumnType("integer");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Vitorias")
                        .HasColumnType("integer");

                    b.HasKey("ClassificacaoId");

                    b.HasIndex("TimeId");

                    b.HasIndex("LigaId", "TimeId")
                        .IsUnique();

                    b.ToTable("LigaClassificacoes");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaEventoPartida", b =>
                {
                    b.Property<Guid>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AssistenteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int?>("Minuto")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("EventoId");

                    b.HasIndex("AssistenteId");

                    b.HasIndex("JogadorId");

                    b.HasIndex("PartidaId");

                    b.HasIndex("TimeId");

                    b.ToTable("LigaEventos");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaGrupoTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Grupo")
                        .HasColumnType("integer");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.HasIndex("LigaId", "Grupo");

                    b.HasIndex("LigaId", "TimeId")
                        .IsUnique();

                    b.ToTable("LigaGruposTimes", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaKnockoutJogo", b =>
                {
                    b.Property<Guid>("KnockoutJogoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Fase")
                        .HasColumnType("integer");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartidaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TimeCasaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TimeForaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VencedorId")
                        .HasColumnType("uuid");

                    b.HasKey("KnockoutJogoId");

                    b.HasIndex("PartidaId");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeForaId");

                    b.HasIndex("VencedorId");

                    b.HasIndex("LigaId", "Fase")
                        .IsUnique();

                    b.ToTable("LigaKnockoutJogos");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaLoteria", b =>
                {
                    b.Property<Guid>("LoteraiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid");

                    b.Property<string>("LigaNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("LoteraiaId");

                    b.ToTable("LigaLoterias", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaLoteriaPick", b =>
                {
                    b.Property<Guid>("PickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoteraiaId")
                        .HasColumnType("uuid");

                    b.Property<int>("PickNumero")
                        .HasColumnType("integer");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer");

                    b.Property<int>("Rodada")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PickId");

                    b.HasIndex("LoteraiaId");

                    b.ToTable("LigaLoteriaPicks", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaPartida", b =>
                {
                    b.Property<Guid>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EncerradaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GolsCasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GolsFora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("IniciadaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsWO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("PenaltisVencedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TemPenaltis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TimeCasaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeForaId")
                        .HasColumnType("uuid");

                    b.HasKey("PartidaId");

                    b.HasIndex("PenaltisVencedorId");

                    b.HasIndex("RodadaId");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeForaId");

                    b.ToTable("LigaPartidas");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaPunicao", b =>
                {
                    b.Property<Guid>("PunicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("PontosSubtraidos")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.HasKey("PunicaoId");

                    b.HasIndex("LigaId");

                    b.HasIndex("TimeId");

                    b.ToTable("LigaPunicoes");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaRodada", b =>
                {
                    b.Property<Guid>("RodadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.HasKey("RodadaId");

                    b.HasIndex("LigaId", "Numero")
                        .IsUnique();

                    b.ToTable("LigaRodadas");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.HasIndex("LigaId", "TimeId")
                        .IsUnique();

                    b.ToTable("LigaTimes", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketBid", b =>
                {
                    b.Property<Guid>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("BidId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ItemId", "CreatedAtUtc");

                    b.ToTable("MarketBids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketCycle", b =>
                {
                    b.Property<Guid>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CycleId");

                    b.ToTable("MarketCycles");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("BuyNowPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentLeaderAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CurrentLeaderTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinIncrement")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId");

                    b.HasIndex("CurrentLeaderTeamId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MarketItems_Player");

                    b.HasIndex("WinnerTeamId");

                    b.HasIndex("CycleId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("CycleId", "Status", "ExpiresAtUtc");

                    b.ToTable("MarketItems");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TargetTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("IX_MarketTransactions_Cycle");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_MarketTransactions_Item");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MarketTransactions_Player");

                    b.HasIndex("PlayerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Player_CreatedAt");

                    b.HasIndex("CycleId", "Type", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Cycle_Type_CreatedAt");

                    b.HasIndex("ItemId", "Type", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Item_Type_CreatedAt");

                    b.ToTable("MarketTransactions");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerGuid")
                        .HasColumnType("uuid");

                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.Property<int?>("QuickSellNewOverall")
                        .HasColumnType("integer");

                    b.Property<int?>("QuickSellOldOverall")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuickSellTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("PlayerId");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("PlayerGuid")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.HasIndex("Name", "PositionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("PositionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = (short)1,
                            Name = "Goleiro"
                        },
                        new
                        {
                            PositionId = (short)2,
                            Name = "Zagueiro"
                        },
                        new
                        {
                            PositionId = (short)3,
                            Name = "Lateral Esquerdo"
                        },
                        new
                        {
                            PositionId = (short)4,
                            Name = "Lateral Direito"
                        },
                        new
                        {
                            PositionId = (short)5,
                            Name = "Volante"
                        },
                        new
                        {
                            PositionId = (short)6,
                            Name = "Meia de Ligação"
                        },
                        new
                        {
                            PositionId = (short)7,
                            Name = "Meia Atacante"
                        },
                        new
                        {
                            PositionId = (short)8,
                            Name = "Meia Esquerda"
                        },
                        new
                        {
                            PositionId = (short)9,
                            Name = "Ponta Esquerda"
                        },
                        new
                        {
                            PositionId = (short)10,
                            Name = "Meia Direita"
                        },
                        new
                        {
                            PositionId = (short)11,
                            Name = "Ponta Direita"
                        },
                        new
                        {
                            PositionId = (short)12,
                            Name = "Centroavante"
                        },
                        new
                        {
                            PositionId = (short)13,
                            Name = "Segundo Atacante"
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.PricingConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("AgeFactor23To24")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgeFactor25To26")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgeFactor27To28")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgeFactor29To30")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgeFactor31To32")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgeFactor33To34")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgeFactor35Plus")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AgeFactorUpTo22")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("BaseScale")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BuyNowFactor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinIncrementRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinIncrementStep")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OverallBase")
                        .HasColumnType("numeric");

                    b.Property<int>("OverallPivot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PricingConfigs");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuxToken")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("AuxiliarName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Budget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BudgetBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OwnerName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("QuickSellCount")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("TransferCount")
                        .HasColumnType("integer");

                    b.HasKey("TeamId");

                    b.HasIndex("AuxToken")
                        .IsUnique();

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineup", b =>
                {
                    b.Property<Guid>("LineupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AttackingPlayer1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("AttackingPlayer2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("AttackingPlayer3Id")
                        .HasColumnType("integer");

                    b.Property<int>("AutoSubstitution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int?>("CaptainPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CornerLeftPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CornerRightPlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Formation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LongFreeKickPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("PenaltiesPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShortFreeKick1PlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShortFreeKick2PlayerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LineupId");

                    b.HasIndex("AttackingPlayer1Id");

                    b.HasIndex("AttackingPlayer2Id");

                    b.HasIndex("AttackingPlayer3Id");

                    b.HasIndex("CaptainPlayerId");

                    b.HasIndex("CornerLeftPlayerId");

                    b.HasIndex("CornerRightPlayerId");

                    b.HasIndex("LongFreeKickPlayerId");

                    b.HasIndex("PenaltiesPlayerId");

                    b.HasIndex("ShortFreeKick1PlayerId");

                    b.HasIndex("ShortFreeKick2PlayerId");

                    b.HasIndex("TeamId", "IsActive")
                        .HasDatabaseName("IX_Lineup_Team_Active");

                    b.ToTable("TeamLineups");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupAdvancedInstructions", b =>
                {
                    b.Property<Guid>("LineupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attack1")
                        .HasColumnType("integer");

                    b.Property<int>("Attack2")
                        .HasColumnType("integer");

                    b.Property<int?>("AttackPlayer1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("AttackPlayer2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Defense1")
                        .HasColumnType("integer");

                    b.Property<int>("Defense2")
                        .HasColumnType("integer");

                    b.Property<int?>("DefensePlayer1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("DefensePlayer2Id")
                        .HasColumnType("integer");

                    b.HasKey("LineupId");

                    b.HasIndex("AttackPlayer1Id");

                    b.HasIndex("AttackPlayer2Id");

                    b.HasIndex("DefensePlayer1Id");

                    b.HasIndex("DefensePlayer2Id");

                    b.ToTable("TeamLineupAdvancedInstructions");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupChangeLog", b =>
                {
                    b.Property<Guid>("ChangeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LineupId")
                        .HasColumnType("uuid");

                    b.HasKey("ChangeLogId");

                    b.HasIndex("LineupId", "ChangedAtUtc")
                        .HasDatabaseName("IX_LineupChangeLog_Lineup_ChangedAt");

                    b.ToTable("TeamLineupChangeLogs");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupDefensiveInstructions", b =>
                {
                    b.Property<Guid>("LineupId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContainmentArea")
                        .HasColumnType("integer");

                    b.Property<int>("DefensiveLine")
                        .HasColumnType("integer");

                    b.Property<int>("DefensiveStyle")
                        .HasColumnType("integer");

                    b.Property<int>("Density")
                        .HasColumnType("integer");

                    b.Property<int>("Pressure")
                        .HasColumnType("integer");

                    b.HasKey("LineupId");

                    b.ToTable("TeamLineupDefensiveInstructions");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupOffensiveInstructions", b =>
                {
                    b.Property<Guid>("LineupId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttackArea")
                        .HasColumnType("integer");

                    b.Property<int>("OffensiveStyle")
                        .HasColumnType("integer");

                    b.Property<int>("Playmaker")
                        .HasColumnType("integer");

                    b.Property<int>("Positioning")
                        .HasColumnType("integer");

                    b.Property<int>("SupportRange")
                        .HasColumnType("integer");

                    b.HasKey("LineupId");

                    b.ToTable("TeamLineupOffensiveInstructions");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupSlot", b =>
                {
                    b.Property<Guid>("LineupSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsBench")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LineupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("LineupSlotId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LineupId", "SlotCode")
                        .IsUnique();

                    b.ToTable("TeamLineupSlots");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MaxQuickSellPerWindow")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTransfers")
                        .HasColumnType("integer");

                    b.Property<int>("MinRosterSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TransferConfigs");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromTeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NewOverall")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("OldOverall")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ToTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("TransferId");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("PerformedAtUtc");

                    b.HasIndex("ToTeamId");

                    b.HasIndex("PlayerId", "PerformedAtUtc");

                    b.ToTable("TransferHistories");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferOffer", b =>
                {
                    b.Property<Guid>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Clauses")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("FromTeamId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Money")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("MoneyPayerTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ParentOfferId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SellOnPercentage")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("OfferId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("ParentOfferId");

                    b.HasIndex("Status");

                    b.HasIndex("ToTeamId");

                    b.ToTable("TransferOffers");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferOfferPlayer", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTarget")
                        .HasColumnType("boolean");

                    b.HasKey("OfferId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("TransferOfferPlayers");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("DraftPicks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("DraftPicks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.DraftRound", "Round")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId", "RoundNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Player");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Rounds")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Liga", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "Campeao")
                        .WithMany()
                        .HasForeignKey("CampeaoTimeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Campeao");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaClassificacao", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Liga", "Liga")
                        .WithMany("Classificacoes")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liga");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaEventoPartida", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "Assistente")
                        .WithMany()
                        .HasForeignKey("AssistenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.LigaPartida", "Partida")
                        .WithMany("Eventos")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assistente");

                    b.Navigation("Jogador");

                    b.Navigation("Partida");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaGrupoTime", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Liga", "Liga")
                        .WithMany("Grupos")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaKnockoutJogo", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Liga", "Liga")
                        .WithMany("KnockoutJogos")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.LigaPartida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "TimeCasa")
                        .WithMany()
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "TimeFora")
                        .WithMany()
                        .HasForeignKey("TimeForaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Vencedor")
                        .WithMany()
                        .HasForeignKey("VencedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Liga");

                    b.Navigation("Partida");

                    b.Navigation("TimeCasa");

                    b.Navigation("TimeFora");

                    b.Navigation("Vencedor");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaLoteriaPick", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.LigaLoteria", "Loteria")
                        .WithMany("Picks")
                        .HasForeignKey("LoteraiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loteria");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaPartida", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "PenaltisVencedor")
                        .WithMany()
                        .HasForeignKey("PenaltisVencedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.LigaRodada", "Rodada")
                        .WithMany("Partidas")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "TimeCasa")
                        .WithMany()
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "TimeFora")
                        .WithMany()
                        .HasForeignKey("TimeForaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PenaltisVencedor");

                    b.Navigation("Rodada");

                    b.Navigation("TimeCasa");

                    b.Navigation("TimeFora");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaPunicao", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Liga", "Liga")
                        .WithMany("Punicoes")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liga");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaRodada", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Liga", "Liga")
                        .WithMany("Rodadas")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaTime", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Liga", "Liga")
                        .WithMany("Times")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketBid", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.MarketItem", "Item")
                        .WithMany("Bids")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("MarketBids")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "CurrentLeaderTeam")
                        .WithMany("LeadingMarketItems")
                        .HasForeignKey("CurrentLeaderTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.MarketCycle", "Cycle")
                        .WithMany("Items")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("MarketItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "WinnerTeam")
                        .WithMany("WonMarketItems")
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentLeaderTeam");

                    b.Navigation("Cycle");

                    b.Navigation("Player");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fc25Draft.Core.Entities.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTeam");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineup", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "AttackingPlayer1")
                        .WithMany()
                        .HasForeignKey("AttackingPlayer1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "AttackingPlayer2")
                        .WithMany()
                        .HasForeignKey("AttackingPlayer2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "AttackingPlayer3")
                        .WithMany()
                        .HasForeignKey("AttackingPlayer3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "CaptainPlayer")
                        .WithMany()
                        .HasForeignKey("CaptainPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "CornerLeftPlayer")
                        .WithMany()
                        .HasForeignKey("CornerLeftPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "CornerRightPlayer")
                        .WithMany()
                        .HasForeignKey("CornerRightPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "LongFreeKickPlayer")
                        .WithMany()
                        .HasForeignKey("LongFreeKickPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "PenaltiesPlayer")
                        .WithMany()
                        .HasForeignKey("PenaltiesPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "ShortFreeKick1Player")
                        .WithMany()
                        .HasForeignKey("ShortFreeKick1PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "ShortFreeKick2Player")
                        .WithMany()
                        .HasForeignKey("ShortFreeKick2PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("Lineups")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttackingPlayer1");

                    b.Navigation("AttackingPlayer2");

                    b.Navigation("AttackingPlayer3");

                    b.Navigation("CaptainPlayer");

                    b.Navigation("CornerLeftPlayer");

                    b.Navigation("CornerRightPlayer");

                    b.Navigation("LongFreeKickPlayer");

                    b.Navigation("PenaltiesPlayer");

                    b.Navigation("ShortFreeKick1Player");

                    b.Navigation("ShortFreeKick2Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupAdvancedInstructions", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "AttackPlayer1")
                        .WithMany()
                        .HasForeignKey("AttackPlayer1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "AttackPlayer2")
                        .WithMany()
                        .HasForeignKey("AttackPlayer2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "DefensePlayer1")
                        .WithMany()
                        .HasForeignKey("DefensePlayer1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "DefensePlayer2")
                        .WithMany()
                        .HasForeignKey("DefensePlayer2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.TeamLineup", "Lineup")
                        .WithOne("AdvancedInstructions")
                        .HasForeignKey("Fc25Draft.Core.Entities.TeamLineupAdvancedInstructions", "LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttackPlayer1");

                    b.Navigation("AttackPlayer2");

                    b.Navigation("DefensePlayer1");

                    b.Navigation("DefensePlayer2");

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupChangeLog", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.TeamLineup", "Lineup")
                        .WithMany()
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupDefensiveInstructions", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.TeamLineup", "Lineup")
                        .WithOne("DefensiveInstructions")
                        .HasForeignKey("Fc25Draft.Core.Entities.TeamLineupDefensiveInstructions", "LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupOffensiveInstructions", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.TeamLineup", "Lineup")
                        .WithOne("OffensiveInstructions")
                        .HasForeignKey("Fc25Draft.Core.Entities.TeamLineupOffensiveInstructions", "LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupSlot", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.TeamLineup", "Lineup")
                        .WithMany("Slots")
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lineup");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("TeamRosters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferOffer", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.TransferOffer", "ParentOffer")
                        .WithMany("CounterOffers")
                        .HasForeignKey("ParentOfferId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromTeam");

                    b.Navigation("ParentOffer");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferOfferPlayer", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.TransferOffer", "Offer")
                        .WithMany("Players")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Navigation("Picks");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Liga", b =>
                {
                    b.Navigation("Classificacoes");

                    b.Navigation("Grupos");

                    b.Navigation("KnockoutJogos");

                    b.Navigation("Punicoes");

                    b.Navigation("Rodadas");

                    b.Navigation("Times");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaLoteria", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaPartida", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.LigaRodada", b =>
                {
                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketCycle", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("MarketItems");

                    b.Navigation("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Navigation("DraftPicks");

                    b.Navigation("LeadingMarketItems");

                    b.Navigation("Lineups");

                    b.Navigation("MarketBids");

                    b.Navigation("Roster");

                    b.Navigation("WonMarketItems");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineup", b =>
                {
                    b.Navigation("AdvancedInstructions");

                    b.Navigation("DefensiveInstructions");

                    b.Navigation("OffensiveInstructions");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferOffer", b =>
                {
                    b.Navigation("CounterOffers");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
