// <auto-generated />
using System;
using Fc25Draft.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fc25Draft.Infra.Migrations
{
    [DbContext(typeof(DraftDbContext))]
    partial class DraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
            {
                b.Property<Guid>("DraftId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("TotalRounds")
                    .HasColumnType("int");

                b.Property<int>("TotalTeams")
                    .HasColumnType("int");

                b.HasKey("DraftId");

                b.ToTable("Drafts");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
            {
                b.Property<Guid>("DraftId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("OverallPick")
                    .HasColumnType("int");

                b.Property<int>("PickInRound")
                    .HasColumnType("int");

                b.Property<int?>("PlayerId")
                    .HasColumnType("int");

                b.Property<DateTime?>("PickedAtUtc")
                    .HasColumnType("datetime2");

                b.Property<int>("RoundNumber")
                    .HasColumnType("int");

                b.Property<Guid>("TeamId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("DraftId", "OverallPick");

                b.HasIndex("DraftId", "RoundNumber", "PickInRound")
                    .IsUnique();

                b.HasIndex("DraftId", "TeamId", "RoundNumber");

                b.HasIndex("PlayerId");

                b.HasIndex("TeamId");

                b.ToTable("DraftPicks");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
            {
                b.Property<Guid>("DraftId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("RoundNumber")
                    .HasColumnType("int");

                b.Property<int?>("OverallMax")
                    .HasColumnType("int");

                b.Property<int?>("OverallMin")
                    .HasColumnType("int");

                b.HasKey("DraftId", "RoundNumber");

                b.ToTable("DraftRounds");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
            {
                var playerId = b.Property<int>("PlayerId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(playerId);

                b.Property<int?>("Age")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.Property<int>("Overall")
                    .HasColumnType("int");

                b.Property<short>("PositionId")
                    .HasColumnType("smallint");

                b.HasKey("PlayerId");

                b.HasIndex("PositionId");

                b.HasIndex("Name", "PositionId");

                b.ToTable("Players");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
            {
                b.Property<short>("PositionId")
                    .HasColumnType("smallint");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("nvarchar(40)");

                b.HasKey("PositionId");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Positions");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
            {
                b.Property<Guid>("TeamId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("OwnerName")
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.Property<string>("TeamName")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.Property<Guid>("TeamToken")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("TeamId");

                b.HasIndex("TeamName")
                    .IsUnique();

                b.HasIndex("TeamToken")
                    .IsUnique();

                b.ToTable("Teams");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
            {
                b.Property<Guid>("TeamId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("PlayerId")
                    .HasColumnType("int");

                b.HasKey("TeamId", "PlayerId");

                b.HasIndex("PlayerId")
                    .IsUnique();

                b.ToTable("TeamRosters");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
            {
                b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                    .WithMany("Picks")
                    .HasForeignKey("DraftId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                    .WithMany("DraftPicks")
                    .HasForeignKey("PlayerId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("Fc25Draft.Core.Entities.DraftRound", "Round")
                    .WithMany("Picks")
                    .HasForeignKey("DraftId", "RoundNumber")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                    .WithMany("DraftPicks")
                    .HasForeignKey("TeamId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Draft");

                b.Navigation("Player");

                b.Navigation("Round");

                b.Navigation("Team");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
            {
                b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                    .WithMany("Rounds")
                    .HasForeignKey("DraftId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Draft");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
            {
                b.HasOne("Fc25Draft.Core.Entities.Position", "Position")
                    .WithMany("Players")
                    .HasForeignKey("PositionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Position");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
            {
                b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                    .WithMany("TeamRosters")
                    .HasForeignKey("PlayerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                    .WithMany("Roster")
                    .HasForeignKey("TeamId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Player");

                b.Navigation("Team");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
            {
                b.Navigation("Picks");

                b.Navigation("Rounds");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
            {
                b.Navigation("DraftPicks");

                b.Navigation("TeamRosters");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
            {
                b.Navigation("Players");
            });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
            {
                b.Navigation("DraftPicks");

                b.Navigation("Roster");
            });
#pragma warning restore 612, 618
        }
    }
}
