// <auto-generated />
using System;
using Fc25Draft.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fc25Draft.Infra.Migrations
{
    [DbContext(typeof(DraftDbContext))]
    partial class DraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminActionsLog", b =>
                {
                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("ActionId");

                    b.HasIndex("ActionType", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AdminActionsLog_ActionType_CreatedAtUtc");

                    b.ToTable("AdminActionsLog", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.AdminToken", b =>
                {
                    b.Property<int>("AdminTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminTokenId"));

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.HasKey("AdminTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Token_Administrador", (string)null);
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.Property<Guid>("BudgetLedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("BudgetLedgerId");

                    b.HasIndex("TeamId");

                    b.ToTable("BudgetLedgers");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Competition", b =>
                {
                    b.Property<Guid>("CompetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("CompetitionId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeasonId", "Name")
                        .IsUnique();

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Round", b =>
                {
                    b.Property<Guid>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime?>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoundId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CompetitionId", "Name")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.RoundSelection", b =>
                {
                    b.Property<Guid>("RoundSelectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.HasKey("RoundSelectionId");

                    b.HasIndex("RoundId")
                        .IsUnique();

                    b.ToTable("RoundSelections");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.RoundSelectionPlayer", b =>
                {
                    b.Property<Guid>("RoundSelectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("RoundSelectionId", "PlayerGuid");

                    b.HasIndex("PlayerGuid");

                    b.HasIndex("RoundSelectionId");

                    b.ToTable("RoundSelectionPlayers");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionLog", b =>
                {
                    b.Property<Guid>("CompetitionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompetitionMatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("CompetitionLogId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CompetitionMatchId");

                    b.ToTable("CompetitionLogs");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionMatch", b =>
                {
                    b.Property<Guid>("CompetitionMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MatchDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observations")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Stadium")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompetitionMatchId");

                    b.HasIndex("AwayCompetitionTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeCompetitionTeamId");

                    b.HasIndex("RoundId", "HomeCompetitionTeamId", "AwayCompetitionTeamId")
                        .IsUnique();

                    b.ToTable("CompetitionMatches");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionMatchEvent", b =>
                {
                    b.Property<Guid>("CompetitionMatchEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int?>("Minute")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompetitionMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observations")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatedPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("CompetitionMatchEventId");

                    b.HasIndex("CompetitionMatchId");

                    b.HasIndex("CompetitionTeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RelatedPlayerId");

                    b.ToTable("CompetitionMatchEvents");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionPlayerStat", b =>
                {
                    b.Property<Guid>("CompetitionPlayerStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer");

                    b.HasKey("CompetitionPlayerStatId");

                    b.HasIndex("CompetitionId", "PlayerId", "CompetitionTeamId")
                        .IsUnique();

                    b.HasIndex("CompetitionTeamId");

                    b.HasIndex("PlayerId");

                    b.ToTable("CompetitionPlayerStats");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionStanding", b =>
                {
                    b.Property<Guid>("CompetitionStandingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer");

                    b.HasKey("CompetitionStandingId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CompetitionTeamId");

                    b.HasIndex("CompetitionId", "Position");

                    b.HasIndex("CompetitionId", "CompetitionTeamId")
                        .IsUnique();

                    b.ToTable("CompetitionStandings");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionTeam", b =>
                {
                    b.Property<Guid>("CompetitionTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("InitialBudget")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CompetitionTeamId");

                    b.HasIndex("CompetitionId", "TeamId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("CompetitionTeams");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionTeamStat", b =>
                {
                    b.Property<Guid>("CompetitionTeamStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer");

                    b.HasKey("CompetitionTeamStatId");

                    b.HasIndex("CompetitionId", "CompetitionTeamId")
                        .IsUnique();

                    b.HasIndex("CompetitionTeamId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("CompetitionTeamStats");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Season", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SeasonId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.SeasonScheduleItem", b =>
                {
                    b.Property<Guid>("SeasonScheduleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("SeasonScheduleItemId");

                    b.HasIndex("RoundId");

                    b.HasIndex("SeasonId", "Order")
                        .IsUnique();

                    b.ToTable("SeasonSchedule");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTeams")
                        .HasColumnType("integer");

                    b.HasKey("DraftId");

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallPick")
                        .HasColumnType("integer");

                    b.Property<int>("PickInRound")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PickedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("DraftId", "OverallPick");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("\"PlayerId\" IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.HasIndex("DraftId", "RoundNumber", "PickInRound")
                        .IsUnique();

                    b.HasIndex("DraftId", "TeamId", "RoundNumber");

                    b.ToTable("DraftPicks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("OverallMax")
                        .HasColumnType("integer");

                    b.Property<int?>("OverallMin")
                        .HasColumnType("integer");

                    b.HasKey("DraftId", "RoundNumber");

                    b.ToTable("DraftRounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketBid", b =>
                {
                    b.Property<Guid>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("BidId");

                    b.HasIndex("TeamId");

                    b.HasIndex("ItemId", "CreatedAtUtc");

                    b.ToTable("MarketBids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketCycle", b =>
                {
                    b.Property<Guid>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CycleId");

                    b.ToTable("MarketCycles");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("BuyNowPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentLeaderAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CurrentLeaderTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MinIncrement")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId");

                    b.HasIndex("CurrentLeaderTeamId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MarketItems_Player");

                    b.HasIndex("WinnerTeamId");

                    b.HasIndex("CycleId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("CycleId", "Status", "ExpiresAtUtc");

                    b.ToTable("MarketItems");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("TargetTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("IX_MarketTransactions_Cycle");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("IX_MarketTransactions_Item");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MarketTransactions_Player");

                    b.HasIndex("PlayerId", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Player_CreatedAt");

                    b.HasIndex("CycleId", "Type", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Cycle_Type_CreatedAt");

                    b.HasIndex("ItemId", "Type", "CreatedAtUtc")
                        .HasDatabaseName("IX_MarketTransactions_Item_Type_CreatedAt");

                    b.ToTable("MarketTransactions");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerGuid")
                        .HasColumnType("uuid");

                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.Property<int?>("QuickSellNewOverall")
                        .HasColumnType("integer");

                    b.Property<int?>("QuickSellOldOverall")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuickSellTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("PlayerId");

                    b.HasIndex("CurrentTeamId");

                    b.HasIndex("PlayerGuid")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.HasIndex("Name", "PositionId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Property<short>("PositionId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("PositionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = (short)1,
                            Name = "Goleiro"
                        },
                        new
                        {
                            PositionId = (short)2,
                            Name = "Zagueiro"
                        },
                        new
                        {
                            PositionId = (short)3,
                            Name = "Lateral/Ala Esquerdo"
                        },
                        new
                        {
                            PositionId = (short)4,
                            Name = "Lateral/Ala Direito"
                        },
                        new
                        {
                            PositionId = (short)5,
                            Name = "Volante"
                        },
                        new
                        {
                            PositionId = (short)6,
                            Name = "Meia Central"
                        },
                        new
                        {
                            PositionId = (short)7,
                            Name = "Meia Atacante"
                        },
                        new
                        {
                            PositionId = (short)8,
                            Name = "Meia/Ponta Esquerda"
                        },
                        new
                        {
                            PositionId = (short)9,
                            Name = "Meia/Ponta Direita"
                        },
                        new
                        {
                            PositionId = (short)10,
                            Name = "Atacante"
                        });
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BudgetBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("OwnerName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineup", b =>
                {
                    b.Property<Guid>("LineupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Formation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TacticCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("CaptainPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CornerLeftPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CornerRightPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("LongFreeKickPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("PenaltiesPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShortFreeKickLeftPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShortFreeKickRightPlayerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LineupId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "IsActive")
                        .HasDatabaseName("IX_Lineup_Team_Active");

                    b.HasIndex("CaptainPlayerId");

                    b.HasIndex("CornerLeftPlayerId");

                    b.HasIndex("CornerRightPlayerId");

                    b.HasIndex("LongFreeKickPlayerId");

                    b.HasIndex("PenaltiesPlayerId");

                    b.HasIndex("ShortFreeKickLeftPlayerId");

                    b.HasIndex("ShortFreeKickRightPlayerId");

                    b.ToTable("TeamLineups");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupSlot", b =>
                {
                    b.Property<Guid>("LineupSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsBench")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LineupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("LineupSlotId");

                    b.HasIndex("LineupId", "SlotCode")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("TeamLineupSlots");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "PlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("FromTeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NewOverall")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("OldOverall")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ToTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("TransferId");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("PerformedAtUtc");

                    b.HasIndex("ToTeamId");

                    b.HasIndex("PlayerId", "PerformedAtUtc");

                    b.ToTable("TransferHistories");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.BudgetLedger", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftPick", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("DraftPicks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("DraftPicks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.DraftRound", "Round")
                        .WithMany("Picks")
                        .HasForeignKey("DraftId", "RoundNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");

                    b.Navigation("Player");

                    b.Navigation("Round");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Draft", "Draft")
                        .WithMany("Rounds")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketBid", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.MarketItem", "Item")
                        .WithMany("Bids")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("MarketBids")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Competition", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Season", "Season")
                        .WithMany("Competitions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logs");

                    b.Navigation("Matches");

                    b.Navigation("Rounds");

                    b.Navigation("Season");

                    b.Navigation("Standings");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionLog", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Competition", "Competition")
                        .WithMany("Logs")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fc25Draft.Core.Entities.CompetitionMatch", "Match")
                        .WithMany()
                        .HasForeignKey("CompetitionMatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Competition");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionMatch", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.CompetitionTeam", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayCompetitionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Competition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.CompetitionTeam", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeCompetitionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");

                    b.Navigation("Events");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionMatchEvent", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.CompetitionMatch", "Match")
                        .WithMany("Events")
                        .HasForeignKey("CompetitionMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("MatchEvents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "RelatedPlayer")
                        .WithMany()
                        .HasForeignKey("RelatedPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.CompetitionTeam", "Team")
                        .WithMany("Events")
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("RelatedPlayer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionPlayerStat", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.CompetitionTeam", "CompetitionTeam")
                        .WithMany("PlayerStats")
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("CompetitionStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("CompetitionTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionStanding", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Competition", "Competition")
                        .WithMany("Standings")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.CompetitionTeam", "CompetitionTeam")
                        .WithMany("Standings")
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("CompetitionTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionTeam", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Competition", "Competition")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("Competitions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("AwayMatches");

                    b.Navigation("Events");

                    b.Navigation("HomeMatches");

                    b.Navigation("PlayerStats");

                    b.Navigation("Standings");

                    b.Navigation("TeamStats");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionTeamStat", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.CompetitionTeam", "CompetitionTeam")
                        .WithMany("TeamStats")
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("CompetitionTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "CurrentLeaderTeam")
                        .WithMany("LeadingMarketItems")
                        .HasForeignKey("CurrentLeaderTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.MarketCycle", "Cycle")
                        .WithMany("Items")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("MarketItems")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "WinnerTeam")
                        .WithMany("WonMarketItems")
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentLeaderTeam");

                    b.Navigation("Cycle");

                    b.Navigation("Player");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "CurrentTeam")
                        .WithMany()
                        .HasForeignKey("CurrentTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fc25Draft.Core.Entities.Position", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionStats");

                    b.Navigation("CurrentTeam");

                    b.Navigation("MatchEvents");

                    b.Navigation("Position");
                    b.Navigation("RoundSelections");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Round", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Competition", "Competition")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Matches");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.RoundSelection", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Round", "Round")
                        .WithOne("Selection")
                        .HasForeignKey("Fc25Draft.Core.Entities.RoundSelection", "RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.RoundSelectionPlayer", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("RoundSelections")
                        .HasPrincipalKey("PlayerGuid")
                        .HasForeignKey("PlayerGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.RoundSelection", "RoundSelection")
                        .WithMany("Players")
                        .HasForeignKey("RoundSelectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("RoundSelection");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.SeasonScheduleItem", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Season", "Season")
                        .WithMany("Schedule")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamRoster", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany("TeamRosters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineup", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Player", "CaptainPlayer")
                        .WithMany()
                        .HasForeignKey("CaptainPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "CornerLeftPlayer")
                        .WithMany()
                        .HasForeignKey("CornerLeftPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "CornerRightPlayer")
                        .WithMany()
                        .HasForeignKey("CornerRightPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "LongFreeKickPlayer")
                        .WithMany()
                        .HasForeignKey("LongFreeKickPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "PenaltiesPlayer")
                        .WithMany()
                        .HasForeignKey("PenaltiesPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "ShortFreeKickLeftPlayer")
                        .WithMany()
                        .HasForeignKey("ShortFreeKickLeftPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "ShortFreeKickRightPlayer")
                        .WithMany()
                        .HasForeignKey("ShortFreeKickRightPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fc25Draft.Core.Entities.Team", "Team")
                        .WithMany("Lineups")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaptainPlayer");

                    b.Navigation("CornerLeftPlayer");

                    b.Navigation("CornerRightPlayer");

                    b.Navigation("LongFreeKickPlayer");

                    b.Navigation("PenaltiesPlayer");

                    b.Navigation("ShortFreeKickLeftPlayer");

                    b.Navigation("ShortFreeKickRightPlayer");

                    b.Navigation("Slots");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TeamLineupSlot", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.TeamLineup", "Lineup")
                        .WithMany("Slots")
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lineup");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.TransferHistory", b =>
                {
                    b.HasOne("Fc25Draft.Core.Entities.Team", "FromTeam")
                        .WithMany()
                        .HasForeignKey("FromTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fc25Draft.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fc25Draft.Core.Entities.Team", "ToTeam")
                        .WithMany()
                        .HasForeignKey("ToTeamId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FromTeam");

                    b.Navigation("Player");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Draft", b =>
                {
                    b.Navigation("Picks");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.DraftRound", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketCycle", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.MarketItem", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Player", b =>
                {
                    b.Navigation("CompetitionStats");

                    b.Navigation("DraftPicks");

                    b.Navigation("MarketItems");

                    b.Navigation("MatchEvents");

                    b.Navigation("RoundSelections");

                    b.Navigation("TeamRosters");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Position", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Team", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("DraftPicks");

                    b.Navigation("LeadingMarketItems");

                    b.Navigation("MarketBids");

                    b.Navigation("Roster");

                    b.Navigation("Lineups");

                    b.Navigation("WonMarketItems");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Competition", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Matches");

                    b.Navigation("Rounds");

                    b.Navigation("Standings");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionMatch", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.CompetitionTeam", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("Events");

                    b.Navigation("HomeMatches");

                    b.Navigation("PlayerStats");

                    b.Navigation("Standings");

                    b.Navigation("TeamStats");
                });

            modelBuilder.Entity("Fc25Draft.Core.Entities.Season", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
